version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: migrate_sqlserver
    volumes:
      - ./docker/sqlserver/init:/init
      - sqlserver:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd
      - TZ=Asia/Tokyo
    networks:
      - migrate-network
    ports:
      - 1433:1433
    entrypoint: /init/entrypoint.sh
  
  mysql:
    image: mysql:5.7.41
    container_name: migrate_mysql
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    tmpfs:
      - /var/lib/mysql,mode=755
      - /var/log/mysql,mode=755  
    environment:
      - MYSQL_DATABASE=db_mysql
      - MYSQL_USER=user_mysql
      - MYSQL_PASSWORD=password_mysql
      - MYSQL_ROOT_PASSWORD=root_password_mysql
      - TZ=Asia/Tokyo
    networks:
      - migrate-network
    ports:
      - 3306:3306

networks:
  migrate-network:
    name: migrate-network

volumes:
  sqlserver:
  mysql: