version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: migrate_sqlserver
    volumes:
      - ./sqlserver/init:/init
      - ./sqlserver:/var/opt/mssql/data
    environment:
      - MSSQL_SA_PASSWORD=password_sqlserver
    networks:
      - migrate-network
    ports:
      - 1433:1433
    entrypoint: /init/entrypoint.sh
  
  mysql:
    image: mysql:8.0.32
    container_name: migrate_mysql
    platform: linux/amd64
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    tmpfs:
      - /var/lib/mysql,mode=755
      - /var/log/mysql,mode=755  
    environment:
      - MYSQL_DATABASE=testdb_mysql
      - MYSQL_USER=testuser_mysql
      - MYSQL_PASSWORD=password_mysql
      - MYSQL_ROOT_PASSWORD=root_password_mysql
    networks:
      - migrate-network
    ports:
      - 3306:3306

networks:
  migrate-network:
    name: migrate-network
